using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Diagnostics;
using Ecommerce.Models;
using Ecommerce.Data;
using Ecommerce.Interfaces;
using Ecommerce.Repository;
using Ecommerce.Services;


var builder = WebApplication.CreateBuilder(args);

// Add Controllers with proper JSON options
builder.Services.AddControllers()
    .AddJsonOptions(opt =>
    {
        opt.JsonSerializerOptions.PropertyNameCaseInsensitive = true;
    });


builder.Services.AddCors(options =>
{
    options.AddPolicy("AllowAngular",
        policy =>
        {
            policy.WithOrigins("http://localhost:4200")
                  .AllowAnyHeader()
                  .AllowAnyMethod()
                  .AllowCredentials();
        });
});

// PostgreSQL connection
builder.Services.AddDbContext<AppDbContext>(options =>
    options.UseNpgsql(builder.Configuration.GetConnectionString("DefaultConnection"))
           .ConfigureWarnings(w => w.Ignore(RelationalEventId.PendingModelChangesWarning))
);

// Dependency Injection
builder.Services.AddScoped<IProductRepository, ProductRepository>();
builder.Services.AddScoped<IProductService, ProductService>();
builder.Services.AddScoped<UserRepository>();
builder.Services.AddScoped<IUserService, UserService>();


// Swagger
// builder.Services.AddEndpointsApiExplorer();
// builder.Services.AddSwaggerGen();

// Build app
var app = builder.Build();

// Middleware
// if (app.Environment.IsDevelopment())
// {
//     app.UseSwagger();
//     app.UseSwaggerUI();
// }

app.UseCors("AllowAngular");

app.UseHttpsRedirection();

app.UseAuthorization();

app.MapControllers();

// DATABASE TABLES CREATION
using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
    Console.WriteLine("[DB Repair] Initializing schema...");
    
    var commands = new[]
    {
        // Shoppings table
        "ALTER TABLE \"Shoppings\" ADD COLUMN IF NOT EXISTS \"UserId\" integer NOT NULL DEFAULT 0;",
        "ALTER TABLE \"Shoppings\" ADD COLUMN IF NOT EXISTS \"ItemType\" text NOT NULL DEFAULT 'Cart';",
        "ALTER TABLE \"Shoppings\" ADD COLUMN IF NOT EXISTS \"Quantity\" integer NOT NULL DEFAULT 1;",
        
        // Orders table (Notice: PaymentDetails is NO LONGER NEEDED here)
        "ALTER TABLE \"Orders\" ADD COLUMN IF NOT EXISTS \"UserId\" integer NOT NULL DEFAULT 0;",
        "ALTER TABLE \"Orders\" ADD COLUMN IF NOT EXISTS \"Status\" text;",
        "ALTER TABLE \"Orders\" ADD COLUMN IF NOT EXISTS \"PaymentMethod\" text;",
        "ALTER TABLE \"Orders\" ADD COLUMN IF NOT EXISTS \"Address\" text;",
        
        // New Payment Tables
        @"CREATE TABLE IF NOT EXISTS ""CodPayments"" (
            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            ""OrderId"" integer NOT NULL,
            ""Note"" text
        );",
        @"CREATE TABLE IF NOT EXISTS ""CardPayments"" (
            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            ""OrderId"" integer NOT NULL,
            ""CardNumber"" text,
            ""CardHolderName"" text,
            ""ExpiryDate"" text
        );"
    };

    foreach (var cmd in commands)
    {
        try 
        { 
            db.Database.ExecuteSqlRaw(cmd);
            Console.WriteLine($"[DB Repair] Success: {cmd.Substring(0, Math.Min(cmd.Length, 50))}...");
        }
        catch (Exception ex) 
        { 
            Console.WriteLine($"[DB Repair] Error: {ex.Message}");
        }
    }

    
    try
    {
        Console.WriteLine("[DB Cleanup] Starting Shoppings cleanup...");
        db.Database.ExecuteSqlRaw(@"
            -- 1. Remove orphaned items (products that don't exist)
            DELETE FROM ""Shoppings"" 
            WHERE ""ProductId"" NOT IN (SELECT ""Id"" FROM ""Products"");

            -- 2. Deduplicate wishlist (keep only one entry per user/product)
            DELETE FROM ""Shoppings"" s1
            USING ""Shoppings"" s2
            WHERE s1.""Id"" > s2.""Id"" 
              AND s1.""UserId"" = s2.""UserId"" 
              AND s1.""ProductId"" = s2.""ProductId"" 
              AND LOWER(s1.""ItemType"") = 'wishlist' 
              AND LOWER(s2.""ItemType"") = 'wishlist';
        ");
        Console.WriteLine("[DB Cleanup] Shoppings cleanup completed successfully.");
    }
    catch (Exception ex)
    {
        Console.WriteLine($"[DB Cleanup] Error: {ex.Message}");
    }
}

app.Run();